package FileShare;

import UserFileInterface.FileManager;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Kerwan Miguel Antoine
 */
public class Login extends javax.swing.JInternalFrame {
    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setForeground(java.awt.Color.white);
        setTitle("Login");
        setBounds(new java.awt.Rectangle(70, 110, 518, 285));
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Grambling_State_Tigers_logo.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(518, 285));
        setVisible(true);
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel3.setBounds(new java.awt.Rectangle(0, 0, 500, 150));
        ImageIcon MyImage = new ImageIcon(getClass().getResource("/grambling.jpg"));
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(), Image.SCALE_SMOOTH);
        jLabel3.setIcon(new ImageIcon(newImg));
        jPanel2.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Login", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout(4, 2));

        jLabel1.setText("Login ID:");
        jPanel3.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setText("Password:");
        jPanel3.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel4.setLayout(new java.awt.BorderLayout(3, 3));

        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jPanel4.add(jTextField1, java.awt.BorderLayout.PAGE_START);

        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
        });
        jPanel4.add(jPasswordField1, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 1, 5);
        flowLayout1.setAlignOnBaseline(true);
        jPanel5.setLayout(flowLayout1);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel6.add(jPanel1);
        getRootPane().setDefaultButton(jButton1);

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);
        this.getRootPane().setDefaultButton(jButton1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTextField1.getText().isEmpty() || jPasswordField1.getPassword().length==0) {
            JOptionPane.showMessageDialog (rootPane, "Please enter all feilds", "Empty Fields", HEIGHT, new ImageIcon(getClass().getResource("/secureShare_logo.png")));
        } else {
            String username = jTextField1.getText();
            char[] password = jPasswordField1.getPassword();
            String userpassword = String.copyValueOf(password);
            if (DBConnection.validateLogin(username, userpassword)) {
                Logger.getLogger(Login.class.getName()).log(Level.INFO, "{0} has logged in", DBConnection.name);
                SecureShare.addToDesktop(SecureShare.fileManager = new FileManager ());
                this.dispose();
                try {
                    SecureShare.welcome.setIcon(true);
                    //ClientConnect ClientInstance = new ClientConnect();
                    //ClientInstance.Connect();
                }
                catch (PropertyVetoException ex) {
                    Logger.getLogger (Login.class.getName()).log (Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Please enter a valid username and password", "Authentication Failed!", HEIGHT , new ImageIcon(getClass().getResource("/secureShare_logo.png")));
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        jTextField1.selectAll ();
    }//GEN-LAST:event_jTextField1FocusGained

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        jPasswordField1.setText ("");
    }//GEN-LAST:event_jPasswordField1FocusGained
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    protected javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
